### ISSUE TITLE
Link Token Not Working

### ISSUE THREAD

**Issue by okezue** [jessica-huynh/Knot#3]
Hello, I'm so sorry to disturb you again with another error. After running the code multiple times, I found that development mode wasn't working and that I was receiving the error that the LinkToken being generated wasn't in the `development` environment, but rather the `sandbox` environment, even after changing it in the Plaid manager file. Any ideas as to why this is happening...? Here is the error: "error_code" = "INVALID_ACCESS_TOKEN";
    "error_message" = "provided access token is for the wrong Plaid environment. expected \"development\", got \"sandbox\"";
    "error_type" = "INVALID_INPUT";
    "request_id" = hGeEsx4xUqcy3KK;
    "suggested_action" = "<null>";
}

**Comment by jessica-huynh** [comment]
When you switch environments, you need to delete the app on the simulator/phone and then run the project and re-link your bank accounts. See if that helps!

**Comment by okezue** [comment]
Oh snap! Thank you so much!

**Comment by okezue** [comment]
I totally forgot to do that!
